### ISSUE TITLE
Cannot Build with Flutter 3.35.2

### ISSUE THREAD

**Issue by And96** [tekartik/sqflite#1184]
After upgrade Flutter 
`
Flutter 3.35.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 05db968908 (5 days ago) • 2025-08-25 10:21:35 -0700
Engine • hash abb725c9a5211af2a862b83f74b7eaf2652db083 (revision a8bfdfc394) (7 days ago) • 2025-08-22 23:51:12.000Z
Tools • Dart 3.9.0 • DevTools 2.48.0
`

Other configurations
`
JavaVersion.VERSION_17
Android SDK 35
gradle-8.7-all.zip
plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "8.6.0" apply false
    id "org.jetbrains.kotlin.android" version "2.1.0" apply false
}
`

When Build APK I get this error
`
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sqflite_android:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights.

BUILD FAILED in 2m 6s
Running Gradle task 'assembleRelease'...                          127,3s
Gradle task assembleRelease failed with exit code 1
`

**Comment by Moyout** [comment]
How did you solve this problem

**Comment by alextekartik** [comment]
You need to update the compile sdk to 36 (which is the default for 3.35). You might have to upgrade the various gradle files according to the new template (AGP 8.12). See this useful gist here: https://gist.github.com/JEuler/82a9e99cae4c68fd67762cfc23de37a0
